# Generated by Django 4.2.6 on 2023-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinbechuser',
            name='phone',
            field=models.BigIntegerField(error_messages='a valid phone number is required'),
        ),
        migrations.AlterField(
            model_name='kinbechuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], error_messages='please choose a valid user type', max_length=10),
        ),
    ]
