# Generated by Django 4.2.6 on 2023-11-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resale_store_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20)),
                ('unit', models.CharField(choices=[('npr', 'NPR'), ('inr', 'INR'), ('usd', 'USD')], default='npr', max_length=3)),
                ('amount', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resale_store_module.resalecar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('note', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payment_module.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
